import type { ReactNode } from "react";

type PathCardProps = {
  icon: ReactNode;
  title: string;
  description: string;
  points: string[];
  cta: string;
};

function PathCard({ icon, title, description, points, cta }: PathCardProps) {
  return (
    <article className="rounded-3xl border border-white/30 bg-[linear-gradient(180deg,rgba(33,72,113,0.52)_0%,rgba(20,49,83,0.88)_100%)] p-6 shadow-[0_18px_48px_rgba(0,0,0,0.28)] sm:p-8">
      <div className="grid gap-7 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)] lg:items-start">
        <div>
          <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-[#0e4f79] text-[#44ece3]">
            {icon}
          </div>
          <h3 className="mt-6 text-3xl font-semibold tracking-tight text-[#e9f5ff]">{title}</h3>
          <p className="mt-3 max-w-lg text-lg leading-relaxed text-[#b7cee5]">{description}</p>
          <button className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#31e0d3] px-7 py-3 text-sm font-semibold text-[#064a56] transition-transform duration-200 hover:-translate-y-0.5">
            <span>{cta}</span>
            <span aria-hidden="true">↗</span>
          </button>
        </div>

        <ul className="space-y-3">
        {points.map((point) => (
          <li
            key={point}
            className="flex items-start gap-3 rounded-2xl border border-[#2a5d86] bg-[#21567f99] px-4 py-3 text-base leading-relaxed text-[#d8edff]"
          >
            <span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#37dace] text-xs font-bold text-[#0a4954]">
              ↗
            </span>
            <span>{point}</span>
          </li>
        ))}
        </ul>
      </div>
    </article>
  );
}

export function TwoPathsSection() {
  return (
    <section className="bg-[var(--suchure-navy)] px-6 py-20 sm:px-10 lg:px-16">
      <div className="mx-auto max-w-6xl space-y-10">
        <div className="text-center">
          <p className="inline-flex rounded-full border border-[#135a86] bg-[#083f64]/70 px-4 py-1.5 text-sm font-semibold text-[#3de8dc]">
            Who Are You?
          </p>
          <h2 className="mt-5 text-4xl font-bold tracking-tight text-[#eef7ff] sm:text-5xl">
            One platform. Two paths to responsible AI.
          </h2>
          <p className="mx-auto mt-4 max-w-3xl text-lg leading-relaxed text-[#b1c7dc]">
            Whether you&apos;re advancing your career or governing your organisation&apos;s AI systems, Suchure
            meets you where you are.
          </p>
        </div>

        <div className="space-y-6">
          <PathCard
            icon={
              <svg viewBox="0 0 24 24" className="h-7 w-7" fill="none" stroke="currentColor" strokeWidth="1.8">
                <path d="M5 20V10m7 10V4m7 16v-7" strokeLinecap="round" />
                <rect x="3" y="8" width="4" height="12" rx="1" />
                <rect x="10" y="2" width="4" height="18" rx="1" />
                <rect x="17" y="11" width="4" height="9" rx="1" />
              </svg>
            }
            title="For Data Professionals"
            description="Build governance-first AI skills that employers in the UK and Nigeria actually need. Move from mid-level to senior in a structured, hands-on programme."
            points={[
              "Personalized career pathway generated by AI",
              "Microsoft Fabric and Azure hands-on labs",
              "Live cohort sessions with senior practitioners",
              "Certification exam preparation with realistic simulations",
              "Community on Microsoft Teams",
            ]}
            cta="Explore Academy"
          />

          <PathCard
            icon={
              <svg viewBox="0 0 24 24" className="h-7 w-7" fill="none" stroke="currentColor" strokeWidth="1.8">
                <path d="M4 19h16M6 19V9l4-3 4 3v10m-6-5h4" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M16 19V6l3-2 1 1v14" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            }
            title="For Regulated Organizations"
            description="Demonstrate that your AI systems are audit-ready, ethical, and compliant. From QuickScan diagnostic to ongoing monitoring, build evidence boards and reports that regulators can trust."
            points={[
              "AI Governance QuickScan diagnostic",
              "Architecture and ethics review via the Assurance Vault",
              "Monthly model bias and drift monitoring dashboard",
              "UK GDPR, EU AI Act, ISO/IEC 42001 alignment",
              "Board-ready evidence and audit log export",
            ]}
            cta="Request a Demo"
          />
        </div>
      </div>
    </section>
  );
}
